version: '2'
services:
  mda:
    image: docker.pkg.github.com/5gzorro/mda/mda_production:latest
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    volumes:
      - ./logs/production:/logs
    expose:
      - "4000"
