version: '2'
services:
  vs:
    #image: docker.pkg.github.com/5gzorro/mda/vs_testing:latest
    build: ./dummy_vs_connector
    ports:
      - "3700:3700"
    expose:
      - "3700"
    links:
      - "mda"
    networks:
      front:
        ipv4_address: 172.253.1.0
      
  osm:
    #image: docker.pkg.github.com/5gzorro/mda/osm_testing:latest
    build: ./dummy_osm_connector
    ports:
      - "4500:4500"
    expose:
      - "4500"
    networks:
      front:
        ipv4_address: 172.253.1.2

  mda:
    #image: docker.pkg.github.com/5gzorro/mda/mda_testing:latest
    build: ./mda
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    volumes:
      - ./logs/development:/logs
    expose:
      - "4000"
    depends_on:
      - osm
    links:
      - "osm"
    networks:
      front:
        ipv4_address: 172.253.1.1
networks:
  front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.253.0.0/16
